package com.beatblock.automap.choreography;

import com.beatblock.automap.AutoMapCandidate;
import com.beatblock.automap.AutoMapCandidateResolver;
import com.beatblock.automap.AutoMapConfig;
import com.beatblock.automap.AutoMapGenerator;
import com.beatblock.automap.AutoMapRule;
import com.beatblock.automap.camera.CameraShot;
import com.beatblock.automap.camera.CameraShotCodec;
import com.beatblock.automap.camera.CameraShotTimelineWriter;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;
import com.beatblock.timeline.TimelineEventOrigin;
import com.beatblock.timeline.generation.TimelineDraftWriter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 将 {@link ChoreographyPlan} 编译为 Timeline 草稿事件。
 */
public final class ChoreographyPlanCompiler {

	private ChoreographyPlanCompiler() {}

	public static int compileAnimationEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		AutoMapConfig config,
		ReplaceMode mode
	) {
		if (timeline == null || plan == null || config == null) return 0;
		ReplaceMode replaceMode = mode != null ? mode : ReplaceMode.APPEND;
		ChoreographyCompileApplicator.applyAnimation(timeline, replaceMode);

		String fallbackTarget = AutoMapGenerator.resolveTargetObjectId();
		Map<String, AutoMapRule> ruleByFeature = indexRules(config);

		List<AutoMapCandidate> candidates = new ArrayList<>(plan.motionPhrases().size());
		for (ChoreographyPlan.MotionPhrase phrase : plan.motionPhrases()) {
			if (!ChoreographyPlanEditor.isMotionEnabled(plan, phrase)) continue;

			double density = plan.densityCurve().sampleAt(phrase.timeSeconds());
			double densityThreshold = ChoreographyPlanEditor.resolveDensityThreshold(plan, phrase, 0.15);
			if (density < densityThreshold) continue;

			AutoMapRule rule = ruleByFeature.get(phrase.normalizedFeatureKey());
			if (rule == null) {
				rule = new AutoMapRule(
					phrase.normalizedFeatureKey(),
					0f,
					phrase.animationTypeId(),
					phrase.durationSeconds(),
					phrase.useEnergyForHeight(),
					phrase.heightMultiplier()
				);
			}
			candidates.add(new AutoMapCandidate(
				phrase.timeSeconds(),
				phrase.trackKey(),
				phrase.normalizedFeatureKey(),
				phrase.energy(),
				rule
			));
		}

		List<AutoMapCandidate> resolved = AutoMapCandidateResolver.resolve(candidates, config.getMinGapSeconds());
		List<TimelineAnimationEvent> draft = new ArrayList<>(resolved.size());
		for (AutoMapCandidate candidate : resolved) {
			AutoMapRule rule = candidate.rule();
			ChoreographyPlan.MotionPhrase sourcePhrase = findMotionPhrase(plan, candidate);
			String animationTypeId = sourcePhrase != null
				? sourcePhrase.animationTypeId()
				: rule.getAnimationTypeId();
			double durationSeconds = sourcePhrase != null
				? sourcePhrase.durationSeconds()
				: rule.getDurationSeconds();
			Map<String, Object> params = new HashMap<>();
			if (rule.isUseEnergyForHeight()) {
				float h = candidate.energy() * rule.getHeightMultiplier();
				params.put("height", h);
			}
			params.put("energy", candidate.energy());

			String targetId = config.resolveTargetObjectId(
				rule,
				candidate.normalizedFeatureKey(),
				fallbackTarget
			);

			double eventTime = BarSnapHelper.snapToNearestBarStart(
				candidate.timeSeconds(),
				plan.musicalStructure(),
				BarSnapHelper.DEFAULT_TOLERANCE_SECONDS
			);

			draft.add(new TimelineAnimationEvent(
				"",
				eventTime,
				durationSeconds,
				animationTypeId,
				targetId,
				candidate.energy(),
				params
			));
		}

		return TimelineDraftWriter.writeAutoGeneratedEvents(timeline, draft, false);
	}

	public static int compileAnimationEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		AutoMapConfig config,
		boolean replace
	) {
		return compileAnimationEvents(
			timeline,
			plan,
			config,
			replace ? ReplaceMode.REPLACE_GENERATED : ReplaceMode.APPEND
		);
	}

	public static int compileCameraEvents(Timeline timeline, ChoreographyPlan plan) {
		return compileCameraEvents(timeline, plan, ReplaceMode.REPLACE_GENERATED);
	}

	public static int compileCameraEvents(Timeline timeline, ChoreographyPlan plan, ReplaceMode mode) {
		if (timeline == null || plan == null || plan.cameraPhrases().isEmpty()) return 0;
		ReplaceMode replaceMode = mode != null ? mode : ReplaceMode.APPEND;
		ChoreographyCompileApplicator.applyCamera(timeline, replaceMode);
		List<CameraShot> shots = new ArrayList<>();
		for (ChoreographyPlan.CameraPhrase phrase : plan.cameraPhrases()) {
			if (!ChoreographyPlanEditor.isCameraEnabled(plan, phrase)) continue;
			shots.add(CameraShotCodec.fromPhrase(phrase));
		}
		return CameraShotTimelineWriter.write(timeline, shots);
	}

	public static int compileVfxEvents(Timeline timeline, ChoreographyPlan plan) {
		return compileVfxEvents(timeline, plan, ReplaceMode.REPLACE_GENERATED);
	}

	public static int compileVfxEvents(Timeline timeline, ChoreographyPlan plan, ReplaceMode mode) {
		if (timeline == null || plan == null || plan.vfxPhrases().isEmpty()) return 0;
		ReplaceMode replaceMode = mode != null ? mode : ReplaceMode.APPEND;
		ChoreographyCompileApplicator.applyVfx(timeline, replaceMode);
		int count = 0;
		for (ChoreographyPlan.VfxPhrase phrase : plan.vfxPhrases()) {
			if (!ChoreographyPlanEditor.isVfxEnabled(plan, phrase)) continue;
			timeline.addGlobalEvent(
				new com.beatblock.timeline.GlobalEvent(
					phrase.timeSeconds(),
					com.beatblock.timeline.GlobalEventType.SPECIAL,
					phrase.vfxKind()
				),
				TimelineEventOrigin.AUTO_GENERATED
			);
			count++;
		}
		return count;
	}

	/** 编译动画、镜头与 VFX 短语（Smart Auto-Map 统一入口）。 */
	public static SmartAutoMapCompileResult compileAll(
		Timeline timeline,
		ChoreographyPlan plan,
		AutoMapConfig config,
		ChoreographyCompileOptions options
	) {
		ChoreographyCompileOptions compileOptions = options != null ? options : ChoreographyCompileOptions.smartAutoMap();
		int animations = compileAnimationEvents(timeline, plan, config, compileOptions.animationMode());
		int cameras = compileCameraEvents(timeline, plan, compileOptions.cameraMode());
		int vfx = compileVfxEvents(timeline, plan, compileOptions.vfxMode());
		return new SmartAutoMapCompileResult(animations, cameras, vfx);
	}

	public static SmartAutoMapCompileResult compileAll(
		Timeline timeline,
		ChoreographyPlan plan,
		AutoMapConfig config,
		boolean replaceAnimations
	) {
		return compileAll(
			timeline,
			plan,
			config,
			replaceAnimations
				? ChoreographyCompileOptions.smartAutoMap()
				: new ChoreographyCompileOptions(
					ReplaceMode.APPEND,
					ReplaceMode.REPLACE_GENERATED,
					ReplaceMode.REPLACE_GENERATED
				)
		);
	}

	public record SmartAutoMapCompileResult(int animationEvents, int cameraEvents, int vfxEvents) {}

	private static Map<String, AutoMapRule> indexRules(AutoMapConfig config) {
		Map<String, AutoMapRule> byFeature = new HashMap<>();
		for (AutoMapRule rule : config.getRules()) {
			byFeature.put(AutoMapGenerator.normalizeFeatureKey(rule.getFeatureKey()), rule);
		}
		return byFeature;
	}

	private static ChoreographyPlan.MotionPhrase findMotionPhrase(ChoreographyPlan plan, AutoMapCandidate candidate) {
		for (ChoreographyPlan.MotionPhrase phrase : plan.motionPhrases()) {
			if (Math.abs(phrase.timeSeconds() - candidate.timeSeconds()) < 1e-6
				&& phrase.normalizedFeatureKey().equals(candidate.normalizedFeatureKey())) {
				return phrase;
			}
		}
		return null;
	}
}
