package com.beatblock.automap.choreography;

import com.beatblock.automap.AutoMapGenerator;
import com.beatblock.automap.choreography.grammar.ChoreographyPhrase;
import com.beatblock.automap.choreography.grammar.PhraseGrammarExpander;
import com.beatblock.automap.choreography.grammar.PhraseTriggerContextFactory;
import com.beatblock.engine.BlockAnimationEngine;
import com.beatblock.automap.camera.CameraShot;
import com.beatblock.automap.camera.CameraShotCodec;
import com.beatblock.automap.camera.CameraShotTimelineWriter;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;
import com.beatblock.timeline.generation.ContentReplacePolicy;
import com.beatblock.timeline.generation.GenerationSession;
import com.beatblock.timeline.generation.TimelineDraftWriter;
import com.beatblock.timeline.generation.TimelineGenerationMetadata;
import com.beatblock.timeline.playback.GlobalEventPayload;

import org.jspecify.annotations.Nullable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 将 {@link ChoreographyPlan} 编译为 Timeline 草稿事件。
 * <p>
 * 动画编译顺序与语义层：
 * <ol>
 *   <li>{@link ChoreographyLayer#ACCENT} — {@link ChoreographyPlan.MotionPhrase}</li>
 *   <li>{@link ChoreographyLayer#PHRASE} — {@link SpatialMotifPhrase}（legacy）与常规 Grammar Phrase</li>
 *   <li>{@link ChoreographyLayer#HERO} — Grammar Phrase with {@link com.beatblock.automap.choreography.grammar.ChoreographyPhrase#isHero()}</li>
 * </ol>
 * Accent / Phrase / Hero 可并存，但默认强度权重不同；展开后由 {@link ChoreographyBudgetEnforcer}
 * 按 {@link DensityCurve} 采样的 {@link ChoreographyBudget} 裁剪过密事件。
 * <p>
 * 编译只读取 Plan（含 {@link ChoreographyPlan#stageRoles()}），不依赖 {@link com.beatblock.automap.AutoMapConfig}。
 */
public final class ChoreographyPlanCompiler {

	private ChoreographyPlanCompiler() {}

	public static int compileAnimationEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ChoreographyCompileOptions options
	) {
		if (timeline == null || plan == null || options == null) return 0;
		GenerationSession session = options.resolveSession(timeline);
		return compileAnimationEvents(
			timeline,
			plan,
			options.animationMode(),
			options.minGapSeconds(),
			session
		);
	}

	public static int compileAnimationEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ReplaceMode mode
	) {
		return compileAnimationEvents(timeline, plan, ChoreographyCompileOptions.animationOnly(mode));
	}

	public static int compileAnimationEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ReplaceMode mode,
		double minGapSeconds
	) {
		if (timeline == null || plan == null) return 0;
		ReplaceMode replaceMode = mode != null ? mode : ReplaceMode.APPEND;
		GenerationSession session = GenerationSession.create(
			com.beatblock.timeline.generation.TimelineGeneratorIds.SMART_AUTOMAP,
			timeline
		);
		return compileAnimationEvents(
			timeline,
			plan,
			replaceMode.toPolicy(),
			minGapSeconds,
			session
		);
	}

	private static int compileAnimationEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ContentReplacePolicy policy,
		double minGapSeconds,
		GenerationSession session
	) {
		ChoreographyCompileApplicator.applyAnimation(timeline, policy);

		String fallbackTarget = AutoMapGenerator.resolveTargetObjectId();
		List<ChoreographyPlan.MotionPhrase> candidates = new ArrayList<>();
		for (ChoreographyPlan.MotionPhrase phrase : plan.motionPhrases()) {
			if (!ChoreographyPlanEditor.isMotionEnabled(plan, phrase)) continue;

			double density = plan.densityCurve().sampleAt(phrase.timeSeconds());
			double densityThreshold = ChoreographyPlanEditor.resolveDensityThreshold(plan, phrase, 0.15);
			if (density < densityThreshold) continue;

			candidates.add(phrase);
		}

		List<ChoreographyPlan.MotionPhrase> resolved = ChoreographyMotionGapResolver.resolve(
			candidates,
			minGapSeconds > 0 ? minGapSeconds : ChoreographyCompileOptions.DEFAULT_MIN_GAP_SECONDS
		);
		List<TimelineAnimationEvent> draft = new ArrayList<>(resolved.size());
		TimingSnapResolver.SnapContext snapContext = TimingSnapResolver.SnapContext.from(plan);
		for (ChoreographyPlan.MotionPhrase phrase : resolved) {
			draft.add(compileMotionPhrase(plan, phrase, fallbackTarget, snapContext, session));
		}
		draft.addAll(compileSpatialMotifPhrases(plan, snapContext, session));
		draft.addAll(compileChoreographyGrammarPhrases(timeline, plan, snapContext, session));
		draft = ChoreographyBudgetEnforcer.enforce(draft, plan);

		return TimelineDraftWriter.writeAutoGeneratedEvents(timeline, draft, false);
	}

	private static TimelineAnimationEvent compileMotionPhrase(
		ChoreographyPlan plan,
		ChoreographyPlan.MotionPhrase phrase,
		String fallbackTarget,
		TimingSnapResolver.SnapContext snapContext,
		GenerationSession session
	) {
		Map<String, Object> params = new HashMap<>();
		if (phrase.useEnergyForHeight()) {
			float h = phrase.energy() * phrase.heightMultiplier();
			params.put("height", h);
		}
		params.put("energy", phrase.energy());

		String targetId = plan.resolveTargetObjectId(phrase.normalizedFeatureKey(), fallbackTarget);

		double eventTime = TimingSnapResolver.snap(
			phrase.timeSeconds(),
			phrase.timingSnap(),
			snapContext
		);

		TimelineGenerationMetadata metadata = session.forPhrase(
			phrase.sectionIndex(),
			plan.musicalPhraseIndexAt(eventTime)
		);
		TimelineAnimationEvent event = new TimelineAnimationEvent(
			"",
			eventTime,
			phrase.durationSeconds(),
			phrase.animationTypeId(),
			targetId,
			phrase.energy(),
			params
		);
		return withLayerMetadata(event, metadata, ChoreographyLayer.ACCENT);
	}

	private static List<TimelineAnimationEvent> compileSpatialMotifPhrases(
		ChoreographyPlan plan,
		TimingSnapResolver.SnapContext snapContext,
		GenerationSession session
	) {
		if (plan.spatialMotifPhrases().isEmpty()) return List.of();
		BlockAnimationEngine animationEngine = SpatialMotifLayoutResolver.currentAnimationEngine();
		List<TimelineAnimationEvent> draft = new ArrayList<>();
		for (SpatialMotifPhrase phrase : plan.spatialMotifPhrases()) {
			if (!ChoreographyPlanEditor.isSpatialMotifEnabled(plan, phrase)) continue;

			double density = plan.densityCurve().sampleAt(phrase.timeSeconds());
			if (density < 0.15) continue;

			double baseTime = TimingSnapResolver.snap(
				phrase.timeSeconds(),
				phrase.timingSnap(),
				snapContext
			);
			SpatialMotifPhrase snapped = new SpatialMotifPhrase(
				baseTime,
				phrase.motifId(),
				phrase.participantIds(),
				phrase.axis(),
				phrase.propagationDelaySeconds(),
				phrase.primitiveId(),
				phrase.phaseMode(),
				phrase.energy(),
				phrase.durationSeconds(),
				phrase.useEnergyForHeight(),
				phrase.heightMultiplier(),
				phrase.sectionIndex(),
				phrase.timingSnap()
			);
			SpatialMotifLayout layout = SpatialMotifLayoutResolver.resolve(
				phrase.participantIds(),
				phrase.axis(),
				animationEngine
			);
			for (SpatialMotifCompiler.ExpandedEvent expanded : SpatialMotifCompiler.expand(snapped, layout)) {
				TimelineGenerationMetadata metadata = session.forPhrase(
					phrase.sectionIndex(),
					plan.musicalPhraseIndexAt(expanded.timeSeconds())
				);
				TimelineAnimationEvent event = new TimelineAnimationEvent(
					"",
					expanded.timeSeconds(),
					expanded.durationSeconds(),
					expanded.primitiveId(),
					expanded.targetObjectId(),
					expanded.energy(),
					expanded.params()
				);
				draft.add(withLayerMetadata(event, metadata, ChoreographyLayer.PHRASE));
			}
		}
		return draft;
	}

	private static List<TimelineAnimationEvent> compileChoreographyGrammarPhrases(
		Timeline timeline,
		ChoreographyPlan plan,
		TimingSnapResolver.SnapContext snapContext,
		GenerationSession session
	) {
		if (timeline == null || plan == null || plan.choreographyPhrases().isEmpty()) {
			return List.of();
		}
		com.beatblock.automap.choreography.grammar.PhraseTriggerContext globalContext =
			com.beatblock.automap.choreography.grammar.PhraseTriggerContextFactory.fromTimeline(
				timeline,
				plan.musicalStructure().beatTimes()
			);
		BlockAnimationEngine animationEngine = SpatialMotifLayoutResolver.currentAnimationEngine();
		List<TimelineAnimationEvent> draft = new ArrayList<>();
		for (com.beatblock.automap.choreography.grammar.ChoreographyPhrase phrase : plan.choreographyPhrases()) {
			if (!ChoreographyPlanEditor.isGrammarPhraseEnabled(plan, phrase)) continue;

			com.beatblock.automap.choreography.grammar.PhraseTriggerContext phraseContext =
				resolveGrammarPhraseTriggerContext(globalContext, plan, phrase);
			com.beatblock.automap.choreography.SpatialMotifLayout layout = SpatialMotifLayoutResolver.resolve(
				phrase.targets().objectIds(),
				phrase.spatial().resolvedAxis(),
				animationEngine
			);
			for (com.beatblock.automap.choreography.grammar.PhraseGrammarExpander.ExpandedPhraseEvent expanded
				: com.beatblock.automap.choreography.grammar.PhraseGrammarExpander.expand(phrase, phraseContext, layout)) {
				double eventTime = TimingSnapResolver.snap(
					expanded.timeSeconds(),
					phrase.timingSnap(),
					snapContext
				);
				TimelineGenerationMetadata metadata = session.forPhrase(
					expanded.sectionIndex(),
					plan.musicalPhraseIndexAt(eventTime)
				);
				TimelineAnimationEvent event = new TimelineAnimationEvent(
					"",
					eventTime,
					expanded.durationSeconds(),
					expanded.primitiveId(),
					expanded.targetObjectId(),
					expanded.energy(),
					expanded.params()
				);
				draft.add(withLayerMetadata(event, metadata, phrase.layer()));
			}
		}
		return draft;
	}

	private static TimelineAnimationEvent withLayerMetadata(
		TimelineAnimationEvent event,
		TimelineGenerationMetadata metadata,
		ChoreographyLayer layer
	) {
		Map<String, Object> params = layer.scaleEventParams(event.getParameters(), event.getEnergy());
		TimelineAnimationEvent scaled = new TimelineAnimationEvent(
			event.getEventId(),
			event.getTimeSeconds(),
			event.getDurationSeconds(),
			event.getAnimationTypeId(),
			event.getTargetObjectId(),
			layer.scaleEnergy(event.getEnergy()),
			params
		);
		return TimelineDraftWriter.withMetadata(scaled, metadata);
	}

	private static com.beatblock.automap.choreography.grammar.PhraseTriggerContext resolveGrammarPhraseTriggerContext(
		com.beatblock.automap.choreography.grammar.PhraseTriggerContext globalContext,
		ChoreographyPlan plan,
		com.beatblock.automap.choreography.grammar.ChoreographyPhrase phrase
	) {
		int sectionIndex = phrase.sectionIndex();
		if (sectionIndex < 0 || sectionIndex >= plan.sections().size()) {
			return globalContext;
		}
		return com.beatblock.automap.choreography.grammar.PhraseTriggerContext.forSection(
			globalContext,
			plan.sections().get(sectionIndex)
		);
	}

	public static int compileCameraEvents(Timeline timeline, ChoreographyPlan plan) {
		return compileCameraEvents(timeline, plan, ReplaceMode.REPLACE_GENERATED);
	}

	public static int compileCameraEvents(Timeline timeline, ChoreographyPlan plan, ReplaceMode mode) {
		return compileCameraEvents(timeline, plan, mode != null ? mode.toPolicy() : ContentReplacePolicy.append(), null);
	}

	public static int compileCameraEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ContentReplacePolicy policy
	) {
		return compileCameraEvents(timeline, plan, policy, null);
	}

	private static int compileCameraEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ContentReplacePolicy policy,
		@Nullable GenerationSession session
	) {
		if (timeline == null || plan == null) return 0;
		ChoreographyCompileApplicator.applyCamera(timeline, policy);
		if (plan.cameraPhrases().isEmpty()) return 0;
		GenerationSession resolved = session != null
			? session
			: GenerationSession.create(
				com.beatblock.timeline.generation.TimelineGeneratorIds.SMART_AUTOMAP,
				timeline
			);
		TimingSnapResolver.SnapContext snapContext = TimingSnapResolver.SnapContext.from(plan);
		List<CameraShotTimelineWriter.TaggedShot> shots = new ArrayList<>();
		for (ChoreographyPlan.CameraPhrase phrase : plan.cameraPhrases()) {
			if (!ChoreographyPlanEditor.isCameraEnabled(plan, phrase)) continue;
			double eventTime = TimingSnapResolver.snap(
				phrase.timeSeconds(),
				phrase.timingSnap(),
				snapContext
			);
			TimelineGenerationMetadata metadata = resolved.forPhrase(
				phrase.sectionIndex(),
				plan.musicalPhraseIndexAt(eventTime)
			);
			shots.add(new CameraShotTimelineWriter.TaggedShot(
				CameraShotCodec.fromPhrase(phrase.withTimeSeconds(eventTime)),
				metadata
			));
		}
		return CameraShotTimelineWriter.writeTagged(timeline, shots);
	}

	public static int compileVfxEvents(Timeline timeline, ChoreographyPlan plan) {
		return compileVfxEvents(timeline, plan, ReplaceMode.REPLACE_GENERATED);
	}

	public static int compileVfxEvents(Timeline timeline, ChoreographyPlan plan, ReplaceMode mode) {
		return compileVfxEvents(timeline, plan, mode != null ? mode.toPolicy() : ContentReplacePolicy.append(), null);
	}

	public static int compileVfxEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ContentReplacePolicy policy
	) {
		return compileVfxEvents(timeline, plan, policy, null);
	}

	private static int compileVfxEvents(
		Timeline timeline,
		ChoreographyPlan plan,
		ContentReplacePolicy policy,
		@Nullable GenerationSession session
	) {
		if (timeline == null || plan == null) return 0;
		ChoreographyCompileApplicator.applyVfx(timeline, policy);
		if (plan.vfxPhrases().isEmpty()) return 0;
		GenerationSession resolved = session != null
			? session
			: GenerationSession.create(
				com.beatblock.timeline.generation.TimelineGeneratorIds.SMART_AUTOMAP,
				timeline
			);
		TimingSnapResolver.SnapContext snapContext = TimingSnapResolver.SnapContext.from(plan);
		int count = 0;
		for (ChoreographyVfx phrase : plan.vfxPhrases()) {
			if (!ChoreographyPlanEditor.isVfxEnabled(plan, phrase)) continue;
			double eventTime = TimingSnapResolver.snap(
				phrase.timeSeconds(),
				TimingSnapDefaults.forVfx(phrase),
				snapContext
			);
			GlobalEventPayload payload = ChoreographyVfxPayloadMapper.toPayload(phrase);
			TimelineGenerationMetadata metadata = resolved.forPhrase(
				phrase.sectionIndex(),
				plan.musicalPhraseIndexAt(eventTime)
			);
			timeline.addGlobalPayloadEvent(eventTime, payload, metadata);
			count++;
		}
		return count;
	}

	/** 编译动画、镜头与 VFX 短语（Smart Auto-Map 统一入口）。 */
	public static SmartAutoMapCompileResult compileAll(
		Timeline timeline,
		ChoreographyPlan plan,
		ChoreographyCompileOptions options
	) {
		ChoreographyCompileOptions compileOptions = options != null ? options : ChoreographyCompileOptions.smartAutoMap();
		GenerationSession session = compileOptions.resolveSession(timeline);
		int animations = compileAnimationEvents(
			timeline,
			plan,
			compileOptions.animationMode(),
			compileOptions.minGapSeconds(),
			session
		);
		int cameras = compileCameraEvents(timeline, plan, compileOptions.cameraMode(), session);
		int vfx = compileVfxEvents(timeline, plan, compileOptions.vfxMode(), session);
		return new SmartAutoMapCompileResult(animations, cameras, vfx);
	}

	/**
	 * 仅重编译指定段落：清除该段 smart-automap 归属内容，并只写入该段短语。
	 */
	public static SmartAutoMapCompileResult compileSection(
		Timeline timeline,
		ChoreographyPlan plan,
		int sectionIndex
	) {
		if (timeline == null || plan == null || sectionIndex < 0) {
			return new SmartAutoMapCompileResult(0, 0, 0);
		}
		return compileAll(
			timeline,
			filterPlanToSection(plan, sectionIndex),
			ChoreographyCompileOptions.forSection(sectionIndex)
		);
	}

	private static ChoreographyPlan filterPlanToSection(ChoreographyPlan plan, int sectionIndex) {
		return new ChoreographyPlan(
			plan.sections(),
			plan.stageRoles(),
			ChoreographyPlanEditor.motionPhrasesInSection(plan, sectionIndex),
			ChoreographyPlanEditor.cameraPhrasesInSection(plan, sectionIndex),
			ChoreographyPlanEditor.vfxPhrasesInSection(plan, sectionIndex),
			plan.densityCurve(),
			plan.sectionEdits(),
			plan.musicalStructure(),
			ChoreographyPlanEditor.spatialMotifPhrasesInSection(plan, sectionIndex),
			ChoreographyPlanEditor.choreographyPhrasesInSection(plan, sectionIndex)
		);
	}

	public record SmartAutoMapCompileResult(int animationEvents, int cameraEvents, int vfxEvents) {}
}
