package com.beatblock.automap.choreography;

import com.beatblock.timeline.Timeline;

/** 将 {@link ReplaceMode} 应用到 Timeline 轨道清理。 */
final class ChoreographyCompileApplicator {

	private ChoreographyCompileApplicator() {}

	static void applyAnimation(Timeline timeline, ReplaceMode mode) {
		if (timeline == null || mode == null) return;
		switch (mode) {
			case APPEND -> { }
			case REPLACE_GENERATED -> timeline.clearAutoAnimationEvents();
			case REPLACE_ALL -> {
				timeline.clearAutoAnimationEvents();
				timeline.clearBlockAnimationEvents();
			}
		}
	}

	static void applyCamera(Timeline timeline, ReplaceMode mode) {
		if (timeline == null || mode == null) return;
		switch (mode) {
			case APPEND -> { }
			case REPLACE_GENERATED -> timeline.clearAutoGeneratedCameraClips();
			case REPLACE_ALL -> timeline.clearCameraKeyframes();
		}
	}

	static void applyVfx(Timeline timeline, ReplaceMode mode) {
		if (timeline == null || mode == null) return;
		switch (mode) {
			case APPEND -> { }
			case REPLACE_GENERATED -> timeline.clearAutoGeneratedGlobalEvents();
			case REPLACE_ALL -> timeline.clearGlobalEvents();
		}
	}
}
