package com.beatblock.automap.engine;

import com.beatblock.audio.analysis.AudioFeatureTimeline;
import com.beatblock.audio.analysis.DetectedBeat;
import com.beatblock.audio.analysis.EnergyFrame;
import com.beatblock.audio.analysis.FrequencyBands;
import com.beatblock.timeline.Timeline;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SmartAutoMapEngineTest {

	@Test
	void generatesAnimationAndCameraEventsFromFeatureTimeline() {
		Timeline timeline = Timeline.createDefault();
		AutoMapSettings settings = new AutoMapSettings();
		settings.setStyle(AutoMapStyle.EDM);
		settings.setComplexity(Complexity.MEDIUM);
		settings.setCameraEnabled(true);
		settings.setParticlesEnabled(false);
		settings.setTargetObjectIds(List.of("stage-main"));

		AudioFeatureTimeline feature = new AudioFeatureTimeline(
			32.0,
			List.of(
				new DetectedBeat(1.0, 0.8f),
				new DetectedBeat(1.5, 0.7f),
				new DetectedBeat(2.0, 0.75f)
			),
			List.of(
				new EnergyFrame(0.0, 0.1f),
				new EnergyFrame(4.0, 0.2f),
				new EnergyFrame(8.0, 0.15f),
				new EnergyFrame(12.0, 0.9f),
				new EnergyFrame(16.0, 0.85f),
				new EnergyFrame(28.0, 0.1f),
				new EnergyFrame(31.0, 0.08f)
			),
			List.of(
				new FrequencyBands(1.0, 0.8f, 0.1f, 0.1f),
				new FrequencyBands(1.5, 0.1f, 0.7f, 0.2f),
				new FrequencyBands(2.0, 0.1f, 0.1f, 0.8f)
			),
			new com.beatblock.audio.analysis.WaveformExtractor.WaveformFrame[0],
			120f,
			null
		);

		SmartAutoMapEngine.AutoMapResult result = SmartAutoMapEngine.generate(feature, settings, timeline);

		assertTrue(result.getAnimationEvents() > 0);
		assertTrue(result.getCameraEvents() > 0);
		assertEquals(0, result.getParticleEvents());
		assertTrue(timeline.getAutoAnimationEvents().size() >= result.getAnimationEvents());
		assertTrue(timeline.getCameraKeyframes().size() >= result.getCameraEvents());
	}

	@Test
	void nullFeatureTimelineClearsAutoGeneratedTracks() {
		Timeline timeline = Timeline.createDefault();
		TimelineBuilder.writeAnimationEvents(
			timeline,
			List.of(new RhythmEvent(1.0, RhythmType.KICK, 0.8f)),
			AutoMapStyle.EDM,
			List.of("stage-main")
		);
		assertEquals(1, timeline.getAutoAnimationEvents().size());

		SmartAutoMapEngine.AutoMapResult result = SmartAutoMapEngine.generate(null, new AutoMapSettings(), timeline);

		assertEquals(0, result.getAnimationEvents());
		assertTrue(timeline.getAutoAnimationEvents().isEmpty());
	}
}
