package com.beatblock.automap.engine;

import com.beatblock.test.WithBeatBlockContext;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.GlobalEvent;
import com.beatblock.timeline.GlobalEventType;
import com.beatblock.timeline.CameraKeyframe;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@WithBeatBlockContext
class TimelineBuilderTest {

	@Test
	void writesAnimationEventsToAutoTrack() {
		Timeline timeline = Timeline.createDefault();
		List<RhythmEvent> rhythm = List.of(
			new RhythmEvent(1.0, RhythmType.KICK, 0.8f),
			new RhythmEvent(2.0, RhythmType.SNARE, 0.7f)
		);

		int count = TimelineBuilder.writeAnimationEvents(timeline, rhythm, AutoMapStyle.EDM, List.of("stage-a"));

		assertEquals(2, count);
		assertEquals(2, timeline.getAutoAnimationEvents().size());
		assertEquals("jump", timeline.getAutoAnimationEvents().get(0).getAnimationTypeId());
		assertEquals("explosion", timeline.getAutoAnimationEvents().get(1).getAnimationTypeId());
	}

	@Test
	void clearAutoGeneratedRemovesAutoTracks() {
		Timeline timeline = Timeline.createDefault();
		TimelineBuilder.writeAnimationEvents(
			timeline,
			List.of(new RhythmEvent(1.0, RhythmType.KICK, 0.5f)),
			AutoMapStyle.EDM,
			List.of("stage-a")
		);
		TimelineBuilder.writeCameraEvents(timeline, List.of(new CameraEvent(3.0, CameraAction.PAN)));

		assertTrue(timeline.getTrack(Timeline.TRACK_ID_CAMERA).getClips().size() >= 1);
		TimelineBuilder.writeParticleEvents(
			timeline,
			List.of(new ParticleEvent(4.0, ParticleType.SPARK))
		);

		TimelineBuilder.clearAutoGenerated(timeline);

		assertTrue(timeline.getAutoAnimationEvents().isEmpty());
		assertTrue(timeline.getTrack(Timeline.TRACK_ID_CAMERA).getClips().isEmpty());
		assertTrue(timeline.getGlobalEvents().isEmpty());
	}

	@Test
	void clearAutoGeneratedPreservesManualCameraAndGlobalEvents() {
		Timeline timeline = Timeline.createDefault();
		timeline.addCameraKeyframe(new CameraKeyframe(1.0));
		timeline.addGlobalEvent(new GlobalEvent(2.0, GlobalEventType.SCREEN_TINT, "Manual Tint"));

		TimelineBuilder.writeCameraEvents(timeline, List.of(new CameraEvent(5.0, CameraAction.ORBIT)));
		TimelineBuilder.writeParticleEvents(timeline, List.of(new ParticleEvent(6.0, ParticleType.SPARK)));

		assertEquals(2, timeline.getTrack(Timeline.TRACK_ID_CAMERA).getClips().size());
		assertEquals(2, timeline.getGlobalEvents().size());

		TimelineBuilder.clearAutoGenerated(timeline);

		assertEquals(1, timeline.getTrack(Timeline.TRACK_ID_CAMERA).getClips().size());
		assertEquals(1, timeline.getGlobalEvents().size());
		assertEquals(1.0, timeline.getCameraKeyframes().getFirst().getTimeSeconds(), 1e-9);
		assertEquals("Manual Tint", timeline.getGlobalEvents().getFirst().getName());
	}
}
