package com.beatblock.automap.engine;

import com.beatblock.timeline.Timeline;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TimelineBuilderTest {

	@Test
	void writesAnimationEventsToAutoTrack() {
		Timeline timeline = Timeline.createDefault();
		List<RhythmEvent> rhythm = List.of(
			new RhythmEvent(1.0, RhythmType.KICK, 0.8f),
			new RhythmEvent(2.0, RhythmType.SNARE, 0.7f)
		);

		int count = TimelineBuilder.writeAnimationEvents(timeline, rhythm, AutoMapStyle.EDM, List.of("stage-a"));

		assertEquals(2, count);
		assertEquals(2, timeline.getAutoAnimationEvents().size());
		assertEquals("jump", timeline.getAutoAnimationEvents().get(0).getAnimationTypeId());
		assertEquals("explosion", timeline.getAutoAnimationEvents().get(1).getAnimationTypeId());
	}

	@Test
	void clearAutoGeneratedRemovesAutoTracks() {
		Timeline timeline = Timeline.createDefault();
		TimelineBuilder.writeAnimationEvents(
			timeline,
			List.of(new RhythmEvent(1.0, RhythmType.KICK, 0.5f)),
			AutoMapStyle.EDM,
			List.of("stage-a")
		);
		TimelineBuilder.writeCameraEvents(timeline, List.of(new CameraEvent(3.0, CameraAction.PAN)));
		TimelineBuilder.writeParticleEvents(
			timeline,
			List.of(new ParticleEvent(4.0, ParticleType.SPARK))
		);

		TimelineBuilder.clearAutoGenerated(timeline);

		assertTrue(timeline.getAutoAnimationEvents().isEmpty());
		assertTrue(timeline.getCameraKeyframes().isEmpty());
		assertTrue(timeline.getGlobalEvents().isEmpty());
	}
}
