package com.beatblock.timeline.generation;

import com.beatblock.test.WithBeatBlockContext;
import com.beatblock.audio.MusicPlayer;
import com.beatblock.runtime.BeatBlockContext;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;
import com.beatblock.timeline.TimelineEditor;
import com.beatblock.timeline.TimelineEventOrigin;
import com.beatblock.timeline.command.CommandManager;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;

@WithBeatBlockContext
class TimelineDraftWriterTest {

	@Test
	void withOriginTagsEventParameters() {
		var source = new TimelineAnimationEvent(
			"ev1", 1.0, 0.5, "build", "stage", 0.8f, Map.of("buildMode", "wall"));
		var tagged = TimelineDraftWriter.withOrigin(source, TimelineEventOrigin.MANUAL);

		assertEquals("MANUAL", tagged.getParameters().get("eventOrigin"));
		assertEquals("wall", tagged.getParameters().get("buildMode"));
		assertNull(TimelineDraftWriter.withOrigin(null, TimelineEventOrigin.MANUAL));
	}

	@Test
	void writeEventsAddsToTimelineWithoutCommandManager() {
		Timeline timeline = Timeline.createDefault();
		var events = List.of(
			new TimelineAnimationEvent("ev1", 2.0, 1.0, "build", "stage", 1f, Map.of()),
			new TimelineAnimationEvent("ev2", 4.0, 0.5, "pulse", "stage", 0.5f, Map.of())
		);

		int written = TimelineDraftWriter.writeEvents(
			timeline,
			Timeline.TRACK_ID_ANIMATION_AUTO,
			events,
			TimelineEventOrigin.AUTO_GENERATED
		);

		assertEquals(2, written);
		assertEquals(2, timeline.getAutoAnimationEvents().size());
		assertEquals("AUTO_GENERATED", timeline.getAutoAnimationEvents().getFirst().getParameters().get("eventOrigin"));
	}

	@Test
	void writeAutoGeneratedEventsCanReplaceExistingTrack() {
		Timeline timeline = Timeline.createDefault();
		timeline.addAutoAnimationEvent(new TimelineAnimationEvent(
			"old", 0.0, 1.0, "build", "stage", 1f, Map.of()));

		int written = TimelineDraftWriter.writeAutoGeneratedEvents(
			timeline,
			List.of(new TimelineAnimationEvent("new", 1.0, 1.0, "build", "stage", 1f, Map.of())),
			true
		);

		assertEquals(1, written);
		assertEquals(1, timeline.getAutoAnimationEvents().size());
		assertEquals(1.0, timeline.getAutoAnimationEvents().getFirst().getTimeSeconds(), 1e-9);
		assertEquals("stage", timeline.getAutoAnimationEvents().getFirst().getTargetObjectId());
	}

	@Test
	void commandManagerOrNullReadsFromInjectedContext() {
		Timeline timeline = Timeline.createDefault();
		MusicPlayer musicPlayer = new MusicPlayer();
		TimelineEditor editor = new TimelineEditor(timeline, musicPlayer);
		BeatBlockContext context = BeatBlockContext.builder()
			.timeline(timeline)
			.timelineEditor(editor)
			.build();

		CommandManager commands = TimelineDraftWriter.commandManagerOrNull(context);

		assertSame(editor.getCommandManager(), commands);
	}
}
