package com.beatblock.automap.engine;

import com.beatblock.audio.analysis.AudioFeatureTimeline;
import com.beatblock.audio.analysis.DetectedBeat;
import com.beatblock.audio.analysis.EnergyFrame;
import com.beatblock.audio.analysis.FrequencyBands;
import com.beatblock.automap.AutoMapConfig;
import com.beatblock.automap.AutoMapConfigFactory;
import com.beatblock.automap.choreography.ChoreographyPlan;
import com.beatblock.automap.choreography.ChoreographyPlanBuilder;
import com.beatblock.automap.choreography.ChoreographyPlanCompiler;
import com.beatblock.automap.choreography.ChoreographyPlanStore;
import com.beatblock.timeline.Timeline;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Smart Auto-Map Engine 门面：音乐 → 编舞计划 → Timeline（方块动画、摄像机、粒子）。
 * <p>
 * 流程：AudioFeatureTimeline → 音乐结构 → {@link ChoreographyPlan} → Timeline Draft。
 */
public final class SmartAutoMapEngine {

	private static final Logger LOGGER = LoggerFactory.getLogger(SmartAutoMapEngine.class);

	/**
	 * 根据音频特征与设置生成完整编排并写入 Timeline。
	 *
	 * @param featureTimeline 来自 Audio Analysis Engine 的分析结果（可为 null，则仅清空不生成）
	 * @param settings        风格、复杂度、镜头/粒子开关
	 * @param timeline        目标时间线
	 * @return 生成统计
	 */
	public static AutoMapResult generate(AudioFeatureTimeline featureTimeline, AutoMapSettings settings, Timeline timeline) {
		AutoMapResult result = new AutoMapResult(0, 0, 0, 0);
		if (timeline == null) return result;
		TimelineBuilder.clearAutoGenerated(timeline);
		if (featureTimeline == null || settings == null) {
			LOGGER.info("BeatBlock Smart Auto-Map: 无音频分析结果或设置，已清空自动轨道");
			return result;
		}
		double duration = featureTimeline.getDurationSeconds();
		float bpm = featureTimeline.getBpm();
		List<FrequencyBands> bands = featureTimeline.getBands();
		List<DetectedBeat> beats = featureTimeline.getBeats();
		List<EnergyFrame> energyFrames = featureTimeline.getEnergyFrames();

		List<StructuralSection> sections = MusicStructureAnalyzer.analyzeSections(featureTimeline);
		List<RhythmEvent> rhythmEvents = RhythmClassifier.classify(beats, bands);
		rhythmEvents = PatternGenerator.filter(rhythmEvents, settings);

		List<CameraEvent> cameraEvents = settings.isCameraEnabled()
			? CameraDirector.generate(sections, bpm, duration, settings.getStyle(), true)
			: List.of();
		List<ParticleEvent> particleEvents = settings.isParticlesEnabled()
			? ParticleDirector.generate(bands, true)
			: List.of();

		AutoMapConfig config = AutoMapConfigFactory.fromSettings(settings);
		ChoreographyPlan plan = ChoreographyPlanBuilder.fromRhythmAnalysis(
			rhythmEvents,
			sections,
			cameraEvents,
			particleEvents,
			settings.getStyle(),
			config
		);

		ChoreographyPlanCompiler.SmartAutoMapCompileResult compiled =
			ChoreographyPlanCompiler.compileAll(timeline, plan, config, false);

		ChoreographyPlanStore.save(timeline, plan, config);

		result = new AutoMapResult(
			compiled.animationEvents(),
			compiled.cameraEvents(),
			compiled.vfxEvents(),
			sections.size()
		);
		LOGGER.info("BeatBlock Smart Auto-Map: 动画 {} 个, 镜头 {} 个, 粒子 {} 个, 段落 {} 个",
			compiled.animationEvents(), compiled.cameraEvents(), compiled.vfxEvents(), sections.size());
		return result;
	}

	/** 生成结果统计 */
	public static final class AutoMapResult {
		private final int animationEvents;
		private final int cameraEvents;
		private final int particleEvents;
		private final int sections;

		public AutoMapResult(int animationEvents, int cameraEvents, int particleEvents, int sections) {
			this.animationEvents = animationEvents;
			this.cameraEvents = cameraEvents;
			this.particleEvents = particleEvents;
			this.sections = sections;
		}

		public int getAnimationEvents() { return animationEvents; }
		public int getCameraEvents() { return cameraEvents; }
		public int getParticleEvents() { return particleEvents; }
		public int getSections() { return sections; }
	}
}
