package com.beatblock.automap.engine;

import com.beatblock.BeatBlock;
import com.beatblock.automap.camera.CameraShot;
import com.beatblock.automap.camera.CameraShotTimelineWriter;
import com.beatblock.automap.choreography.ChoreographyVfx;
import com.beatblock.automap.choreography.ChoreographyVfxFactory;
import com.beatblock.automap.choreography.ChoreographyVfxPayloadMapper;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;
import com.beatblock.timeline.TimelineEventOrigin;
import com.beatblock.timeline.playback.GlobalEventPayload;
import com.beatblock.timeline.generation.TimelineDraftWriter;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 将自动编排结果写入 Timeline：动画事件、摄像机关键帧、全局事件（粒子/灯光）。
 */
public final class TimelineBuilder {

	/**
	 * 清空自动动画、摄像机、全局事件轨道（为重新生成做准备）。
	 */
	public static void clearAutoGenerated(Timeline timeline) {
		if (timeline == null) return;
		timeline.clearAutoAnimationEvents();
		timeline.clearAutoGeneratedCameraClips();
		timeline.clearAutoGeneratedGlobalEvents();
	}

	/**
	 * 写入动画事件到自动动画轨道。
	 */
	public static int writeAnimationEvents(Timeline timeline, List<RhythmEvent> rhythmEvents,
	                                       AutoMapStyle style, List<String> targetObjectIds) {
		if (timeline == null || rhythmEvents == null || rhythmEvents.isEmpty()) return 0;
		String targetId = resolveTargetId(targetObjectIds);
		List<TimelineAnimationEvent> events = new java.util.ArrayList<>(rhythmEvents.size());
		for (RhythmEvent e : rhythmEvents) {
			String animId = AnimationMapper.getAnimationTypeId(e, style);
			double dur = AnimationMapper.getDurationSeconds(e.getType(), style);
			Map<String, Object> params = new HashMap<>();
			params.put("energy", e.getEnergy());
			events.add(new TimelineAnimationEvent(
				"",
				e.getTimeSeconds(),
				dur,
				animId,
				targetId,
				e.getEnergy(),
				params
			));
		}
		return TimelineDraftWriter.writeAutoGeneratedEvents(timeline, events, false);
	}

	/**
	 * 写入带主体语义的镜头片段到摄像机轨道。
	 */
	public static int writeCameraEvents(Timeline timeline, List<CameraEvent> cameraEvents) {
		if (timeline == null || cameraEvents == null) return 0;
		List<CameraShot> shots = new java.util.ArrayList<>(cameraEvents.size());
		for (CameraEvent event : cameraEvents) {
			if (event != null) shots.add(event.getShot());
		}
		return CameraShotTimelineWriter.write(timeline, shots);
	}

	/**
	 * 写入粒子事件为强类型全局 payload（PARTICLE_BURST）。
	 */
	public static int writeParticleEvents(Timeline timeline, List<ParticleEvent> particleEvents) {
		if (timeline == null || particleEvents == null) return 0;
		int count = 0;
		for (ParticleEvent e : particleEvents) {
			ChoreographyVfx.ParticleBurst phrase = ChoreographyVfxFactory.fromParticleEvent(
				e, -1, List.of());
			GlobalEventPayload payload = ChoreographyVfxPayloadMapper.toPayload(phrase);
			timeline.addGlobalPayloadEvent(e.getTimeSeconds(), payload, TimelineEventOrigin.GENERATED);
			count++;
		}
		return count;
	}

	private static String resolveTargetId(List<String> targetObjectIds) {
		if (targetObjectIds != null && !targetObjectIds.isEmpty()) {
			for (String id : targetObjectIds) {
				if (id != null && !id.isBlank()) return id;
			}
		}
		var engine = BeatBlock.getContext().blockAnimationEngine();
		if (engine != null) {
			var sys = engine.getStageObjectSystem();
			var all = sys != null ? sys.getAll() : null;
			if (all != null && !all.isEmpty()) return all.iterator().next().getId();
		}
		return "";
	}
}
