package com.beatblock.timeline;

import com.beatblock.test.WithBeatBlockContext;
import com.beatblock.timeline.camera.CameraTrackFactory;
import com.beatblock.timeline.generation.GenerationSession;
import com.beatblock.timeline.generation.TimelineDraftWriter;
import com.beatblock.timeline.generation.TimelineGeneratorIds;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@WithBeatBlockContext
class TimelineClipOriginTest {

	@Test
	void distinguishesManualAndAutoGeneratedCameraClips() {
		Timeline timeline = Timeline.createDefault();
		timeline.addCameraKeyframe(new CameraKeyframe(1.0));
		CameraTrackFactory.addPathSegment(
			timeline, 4.0, 3.0, 0, 64, 0, 0, 0, "SMOOTH", TimelineEventOrigin.GENERATED);

		var clips = timeline.getTrack(Timeline.TRACK_ID_CAMERA).getClips();
		assertEquals(2, clips.size());
		assertFalse(TimelineClipOrigin.isAutoGenerated(clips.get(0), Timeline.TRACK_ID_CAMERA));
		assertTrue(TimelineClipOrigin.isAutoGenerated(clips.get(1), Timeline.TRACK_ID_CAMERA));
	}

	@Test
	void distinguishesManualAndAutoGeneratedGlobalEvents() {
		Timeline timeline = Timeline.createDefault();
		timeline.addGlobalEvent(new GlobalEvent(1.0, GlobalEventType.SCREEN_TINT, "Manual"));
		timeline.addGlobalEvent(
			new GlobalEvent(2.0, GlobalEventType.SPECIAL, "Auto"),
			TimelineEventOrigin.GENERATED
		);

		var clips = timeline.getTrack(Timeline.TRACK_ID_GLOBAL).getClips();
		assertEquals(2, clips.size());
		assertFalse(TimelineClipOrigin.isAutoGenerated(clips.get(0), Timeline.TRACK_ID_GLOBAL));
		assertTrue(TimelineClipOrigin.isAutoGenerated(clips.get(1), Timeline.TRACK_ID_GLOBAL));
	}

	@Test
	void readsGenerationMetadataFromAnimationBlockClips() {
		Timeline timeline = Timeline.createDefault();
		var session = GenerationSession.create(TimelineGeneratorIds.RHYTHM_DROP, timeline);
		var event = TimelineDraftWriter.withMetadata(
			new TimelineAnimationEvent("e1", 1.0, 0.5, "RhythmDrop", "anchor", 1f, Map.of()),
			session.forBatch()
		);
		TimelineDraftWriter.insertGeneratedEvents(
			timeline,
			Timeline.TRACK_ID_ANIMATION_BLOCK,
			List.of(event)
		);

		var clips = timeline.getTrack(Timeline.TRACK_ID_ANIMATION_BLOCK).getClips();
		assertEquals(1, clips.size());
		assertTrue(TimelineClipOrigin.isAutoGenerated(clips.get(0), Timeline.TRACK_ID_ANIMATION_BLOCK));
		var metadata = TimelineClipOrigin.metadataFromClip(clips.get(0), Timeline.TRACK_ID_ANIMATION_BLOCK);
		assertEquals(TimelineGeneratorIds.RHYTHM_DROP, metadata.generatorId());
		assertEquals(session.generationId(), metadata.generationId());
	}
}
