package com.beatblock.timeline;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TimelineEventOriginTest {

	@Test
	void fromValueParsesCanonicalValues() {
		assertEquals(TimelineEventOrigin.MANUAL, TimelineEventOrigin.fromValue("MANUAL"));
		assertEquals(TimelineEventOrigin.GENERATED, TimelineEventOrigin.fromValue("generated"));
		assertEquals(TimelineEventOrigin.IMPORTED, TimelineEventOrigin.fromValue("imported"));
	}

	@Test
	void fromValueMapsLegacyGeneratedAliases() {
		assertEquals(TimelineEventOrigin.GENERATED, TimelineEventOrigin.fromValue("AUTO_GENERATED"));
		assertEquals(TimelineEventOrigin.GENERATED, TimelineEventOrigin.fromValue("auto_map"));
		assertEquals(TimelineEventOrigin.GENERATED, TimelineEventOrigin.fromValue("AI_GENERATED"));
		assertEquals(TimelineEventOrigin.GENERATED, TimelineEventOrigin.fromValue("template"));
		assertEquals(TimelineEventOrigin.GENERATED, TimelineEventOrigin.fromValue("SCRIPT"));
	}

	@Test
	void fromValueMapsLegacyImportedAliases() {
		assertEquals(TimelineEventOrigin.IMPORTED, TimelineEventOrigin.fromValue("OSC"));
		assertEquals(TimelineEventOrigin.IMPORTED, TimelineEventOrigin.fromValue("osc_import"));
	}

	@Test
	void fromValueDefaultsToManualForNullBlankOrUnknown() {
		assertEquals(TimelineEventOrigin.MANUAL, TimelineEventOrigin.fromValue(null));
		assertEquals(TimelineEventOrigin.MANUAL, TimelineEventOrigin.fromValue(""));
		assertEquals(TimelineEventOrigin.MANUAL, TimelineEventOrigin.fromValue("  "));
		assertEquals(TimelineEventOrigin.MANUAL, TimelineEventOrigin.fromValue("draft"));
	}

	@Test
	void deprecatedAutoGeneratedAliasPointsToGenerated() {
		assertEquals(TimelineEventOrigin.GENERATED, TimelineEventOrigin.AUTO_GENERATED);
	}

	@Test
	void replaceableByGenerationExcludesImported() {
		assertTrue(TimelineEventOrigin.GENERATED.isReplaceableByGeneration());
		assertFalse(TimelineEventOrigin.IMPORTED.isReplaceableByGeneration());
		assertFalse(TimelineEventOrigin.MANUAL.isReplaceableByGeneration());
	}
}
