package com.beatblock.timeline.generation;

import com.beatblock.BeatBlock;
import com.beatblock.runtime.BeatBlockContext;
import com.beatblock.timeline.AnimationEventParams;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;
import com.beatblock.timeline.TimelineEventOrigin;
import com.beatblock.timeline.command.AddTimelineAnimationEventCommand;
import com.beatblock.timeline.command.ClearAnimationTrackCommand;
import com.beatblock.timeline.command.Command;
import com.beatblock.timeline.command.CommandManager;
import com.beatblock.timeline.command.CompositeCommand;
import com.beatblock.timeline.editing.TimelineDocumentChangeNotifier;

import org.jspecify.annotations.Nullable;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Timeline animation-event write paths via {@link CommandManager}.
 * <p>
 * Use {@link #writeUserEvents} for UI-triggered committed inserts (Animation Library,
 * Event Library, record mode) — those notify {@link TimelineDocumentChangeNotifier}.
 * Use {@link #writeGeneratedEvents} for draft / auto-generation internal writes that
 * must not fire document-change side effects by themselves.
 */
public final class TimelineDraftWriter {

	private TimelineDraftWriter() {}

	public static int writeAutoGeneratedEvents(
		Timeline timeline,
		List<TimelineAnimationEvent> events,
		boolean replaceExisting
	) {
		if (timeline == null || events == null || events.isEmpty()) return 0;
		if (replaceExisting) {
			clearTrack(timeline, Timeline.TRACK_ID_ANIMATION_AUTO);
		}
		return writeGeneratedEvents(timeline, Timeline.TRACK_ID_ANIMATION_AUTO, events, TimelineEventOrigin.GENERATED);
	}

	public static void clearTrack(Timeline timeline, String trackId) {
		if (timeline == null || trackId == null) return;
		CommandManager commands = commandManagerOrNull();
		if (commands != null) {
			commands.execute(new ClearAnimationTrackCommand(timeline, trackId));
		} else {
			timeline.clearAnimationTrack(trackId);
		}
	}

	/**
	 * UI-triggered committed insertion. Notifies document change when at least one event is written.
	 */
	public static boolean writeUserEvent(
		Timeline timeline,
		String trackId,
		TimelineAnimationEvent event,
		TimelineEventOrigin origin
	) {
		if (event == null) return false;
		return writeUserEvents(timeline, trackId, List.of(event), origin) > 0;
	}

	/**
	 * UI-triggered committed insertion. Notifies document change once when {@code written > 0}.
	 */
	public static int writeUserEvents(
		Timeline timeline,
		String trackId,
		List<TimelineAnimationEvent> events,
		TimelineEventOrigin origin
	) {
		int written = writeEvents(timeline, trackId, events, origin != null ? origin : TimelineEventOrigin.MANUAL);
		if (written > 0) {
			TimelineDocumentChangeNotifier.notifyDocumentEdited();
		}
		return written;
	}

	/**
	 * Draft / auto-generation internal write. Does not notify document change.
	 */
	public static int writeGeneratedEvents(
		Timeline timeline,
		String trackId,
		List<TimelineAnimationEvent> events,
		TimelineEventOrigin origin
	) {
		return writeEvents(timeline, trackId, events, origin != null ? origin : TimelineEventOrigin.GENERATED);
	}

	/**
	 * Low-level single-event write (no document-change notify). Prefer
	 * {@link #writeUserEvent} or {@link #writeGeneratedEvents}.
	 */
	public static boolean writeEvent(
		Timeline timeline,
		String trackId,
		TimelineAnimationEvent event,
		TimelineEventOrigin origin
	) {
		return writeEvents(
			timeline,
			trackId,
			event != null ? List.of(event) : List.of(),
			origin
		) > 0;
	}

	/**
	 * Low-level batch write as one {@link CompositeCommand} (no document-change notify).
	 * Prefer {@link #writeUserEvents} or {@link #writeGeneratedEvents}.
	 */
	public static int writeEvents(
		Timeline timeline,
		String trackId,
		List<TimelineAnimationEvent> events,
		TimelineEventOrigin origin
	) {
		if (timeline == null || trackId == null || events == null || events.isEmpty()) return 0;
		TimelineEventOrigin resolved = origin != null ? origin : TimelineEventOrigin.GENERATED;
		List<Command> parts = new ArrayList<>(events.size());
		for (TimelineAnimationEvent event : events) {
			if (event == null) continue;
			TimelineAnimationEvent tagged = tagForWrite(event, resolved);
			if (tagged == null) continue;
			parts.add(new AddTimelineAnimationEventCommand(timeline, trackId, tagged));
		}
		if (parts.isEmpty()) return 0;

		CompositeCommand composite = new CompositeCommand(parts);
		CommandManager commands = commandManagerOrNull();
		if (commands != null) {
			commands.execute(composite);
		} else {
			composite.execute();
		}
		timeline.sortAll();
		return parts.size();
	}

	private static @Nullable TimelineAnimationEvent tagForWrite(
		TimelineAnimationEvent event,
		TimelineEventOrigin origin
	) {
		TimelineGenerationMetadata existing = TimelineGenerationMetadata.fromParameters(event.getParameters());
		if (existing.generatorId().isBlank() && existing.generationId().isBlank()) {
			return withOrigin(event, origin);
		}
		return event;
	}

	public static @Nullable TimelineAnimationEvent withOrigin(
		@Nullable TimelineAnimationEvent source,
		@Nullable TimelineEventOrigin origin
	) {
		if (source == null) return null;
		TimelineEventOrigin resolved = origin != null ? origin : TimelineEventOrigin.GENERATED;
		return withMetadata(source, TimelineGenerationMetadata.fromOrigin(resolved));
	}

	public static @Nullable TimelineAnimationEvent withMetadata(
		@Nullable TimelineAnimationEvent source,
		@Nullable TimelineGenerationMetadata metadata
	) {
		if (source == null) return null;
		Map<String, Object> params = TimelineGenerationMetadataSupport.apply(
			AnimationEventParams.fromAnimationEvent(source).toParameterMap(),
			metadata
		);
		AnimationEventParams parsed = AnimationEventParams.fromParameterMap(params);
		return new TimelineAnimationEvent(
			source.getEventId(),
			source.getTimeSeconds(),
			parsed.durationSeconds(),
			parsed.animationType(),
			parsed.targetObject(),
			parsed.energy(),
			parsed.toParameterMap()
		);
	}

	private static @Nullable CommandManager commandManagerOrNull() {
		return commandManagerOrNull(BeatBlock.getContext());
	}

	static @Nullable CommandManager commandManagerOrNull(@Nullable BeatBlockContext context) {
		if (context == null) return null;
		return context.commandManager();
	}
}
