package com.beatblock.timeline.generation;

import com.beatblock.BeatBlock;
import com.beatblock.runtime.BeatBlockContext;
import com.beatblock.timeline.AnimationEventParams;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;
import com.beatblock.timeline.TimelineEventOrigin;
import com.beatblock.timeline.command.AddTimelineAnimationEventCommand;
import com.beatblock.timeline.command.ClearAnimationTrackCommand;
import com.beatblock.timeline.command.CommandManager;

import java.util.List;

/**
 * 草稿生成器统一写入路径：自动/批量事件经 {@link com.beatblock.timeline.command.CommandManager} 写入 Timeline。
 */
public final class TimelineDraftWriter {

	private TimelineDraftWriter() {}

	public static int writeAutoGeneratedEvents(
		Timeline timeline,
		List<TimelineAnimationEvent> events,
		boolean replaceExisting
	) {
		if (timeline == null || events == null || events.isEmpty()) return 0;
		if (replaceExisting) {
			clearTrack(timeline, Timeline.TRACK_ID_ANIMATION_AUTO);
		}
		return writeEvents(timeline, Timeline.TRACK_ID_ANIMATION_AUTO, events, TimelineEventOrigin.AUTO_GENERATED);
	}

	public static void clearTrack(Timeline timeline, String trackId) {
		if (timeline == null || trackId == null) return;
		CommandManager commands = commandManagerOrNull();
		if (commands != null) {
			commands.execute(new ClearAnimationTrackCommand(timeline, trackId));
		} else {
			timeline.clearAnimationTrack(trackId);
		}
	}

	public static boolean writeEvent(
		Timeline timeline,
		String trackId,
		TimelineAnimationEvent event,
		TimelineEventOrigin origin
	) {
		if (timeline == null || trackId == null || event == null) return false;
		TimelineAnimationEvent tagged = withOrigin(event, origin != null ? origin : TimelineEventOrigin.AUTO_GENERATED);
		CommandManager commands = commandManagerOrNull();
		if (commands != null) {
			commands.execute(new AddTimelineAnimationEventCommand(timeline, trackId, tagged));
		} else {
			timeline.addAnimationEvent(trackId, tagged);
		}
		return true;
	}

	public static int writeEvents(
		Timeline timeline,
		String trackId,
		List<TimelineAnimationEvent> events,
		TimelineEventOrigin origin
	) {
		if (timeline == null || trackId == null || events == null || events.isEmpty()) return 0;
		int count = 0;
		for (TimelineAnimationEvent event : events) {
			if (writeEvent(timeline, trackId, event, origin)) count++;
		}
		if (count > 0) timeline.sortAll();
		return count;
	}

	public static TimelineAnimationEvent withOrigin(TimelineAnimationEvent source, TimelineEventOrigin origin) {
		if (source == null) return null;
		TimelineEventOrigin resolved = origin != null ? origin : TimelineEventOrigin.AUTO_GENERATED;
		AnimationEventParams params = AnimationEventParams.fromAnimationEvent(source).withEventOrigin(resolved);
		return new TimelineAnimationEvent(
			source.getEventId(),
			source.getTimeSeconds(),
			params.durationSeconds(),
			params.animationType(),
			params.targetObject(),
			params.energy(),
			params.toParameterMap()
		);
	}

	private static CommandManager commandManagerOrNull() {
		return commandManagerOrNull(BeatBlock.getContext());
	}

	static CommandManager commandManagerOrNull(BeatBlockContext context) {
		if (context == null) return null;
		return context.commandManager();
	}
}
