package com.beatblock.timeline.command;

import com.beatblock.audio.analysis.AudioFeatureTimeline;
import com.beatblock.audio.analysis.DetectedBeat;
import com.beatblock.audio.analysis.EnergyFrame;
import com.beatblock.audio.analysis.FrequencyBands;
import com.beatblock.automap.engine.AutoMapSettings;
import com.beatblock.engine.BlockAnimationEngine;
import com.beatblock.test.WithBeatBlockContext;
import com.beatblock.testutil.MinecraftTestBootstrap;
import com.beatblock.timeline.CameraKeyframe;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineEditor;
import com.beatblock.timeline.project.golden.GoldenProjectEventCounts;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@WithBeatBlockContext
class SmartAutoMapGenerateCommandTest {

	@BeforeAll
	static void bootstrapMinecraft() {
		MinecraftTestBootstrap.ensureInitialized();
	}

	@Test
	void oneGenerateIsOneUndoStepAndRestoresManualContent() {
		Timeline timeline = Timeline.createDefault();
		timeline.setDurationSeconds(16);
		timeline.addCameraKeyframe(new CameraKeyframe(1.0));
		assertEquals(1, GoldenProjectEventCounts.camera(timeline).manual());

		TimelineEditor editor = new TimelineEditor(timeline);
		CommandManager commands = editor.getCommandManager();
		BlockAnimationEngine engine = new BlockAnimationEngine();

		AutoMapSettings settings = new AutoMapSettings();
		settings.setCameraEnabled(true);
		settings.setParticlesEnabled(true);

		int undoBefore = commands.undoCount();
		SmartAutoMapGenerateCommand command = SmartAutoMapGenerateCommand.runAndCapture(
			sampleFeatures(16.0),
			settings,
			timeline,
			engine.getBuildLayerManager()
		);
		commands.execute(command);

		assertEquals(undoBefore + 1, commands.undoCount());
		assertTrue(
			GoldenProjectEventCounts.camera(timeline).autoGenerated() > 0
				|| timeline.getAutoAnimationEvents().size() > 0
				|| GoldenProjectEventCounts.global(timeline).autoGenerated() > 0
		);
		assertEquals(1, GoldenProjectEventCounts.camera(timeline).manual());

		commands.undo();
		assertEquals(1, GoldenProjectEventCounts.camera(timeline).manual());
		assertEquals(0, GoldenProjectEventCounts.camera(timeline).autoGenerated());
		assertEquals(0, timeline.getAutoAnimationEvents().size());

		commands.redo();
		assertEquals(1, GoldenProjectEventCounts.camera(timeline).manual());
		assertTrue(
			GoldenProjectEventCounts.camera(timeline).autoGenerated() > 0
				|| timeline.getAutoAnimationEvents().size() > 0
				|| GoldenProjectEventCounts.global(timeline).autoGenerated() > 0
		);
		assertEquals(undoBefore + 1, commands.undoCount());
	}

	@Test
	void commandDescriptionIsStable() {
		assertEquals(
			com.beatblock.ui.i18n.BBTexts.get("beatblock.undo.smart_automap_generate"),
			CommandDescriptions.describe(SmartAutoMapGenerateCommand.runAndCapture(
				null, null, Timeline.createDefault(), null))
		);
	}

	private static AudioFeatureTimeline sampleFeatures(double durationSeconds) {
		return new AudioFeatureTimeline(
			durationSeconds,
			List.of(
				new DetectedBeat(0.5, 1f),
				new DetectedBeat(1.0, 1f),
				new DetectedBeat(2.0, 0.8f),
				new DetectedBeat(4.0, 1f),
				new DetectedBeat(8.0, 1f)
			),
			List.of(
				new EnergyFrame(0.0, 0.4f),
				new EnergyFrame(4.0, 0.7f),
				new EnergyFrame(8.0, 0.9f)
			),
			List.of(
				new FrequencyBands(0.5, 0.4f, 0.3f, 0.2f),
				new FrequencyBands(1.0, 0.6f, 0.5f, 0.4f)
			),
			new com.beatblock.audio.analysis.WaveformExtractor.WaveformFrame[0],
			120f,
			null
		);
	}
}
