package com.beatblock.timeline.project.golden;

import com.beatblock.timeline.Clip;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineClipOrigin;
import com.beatblock.timeline.Track;

/** Count manual vs auto-generated camera / global clips on a timeline. */
public final class GoldenProjectEventCounts {

	public record OriginCounts(int manual, int autoGenerated) {
		public static OriginCounts zero() {
			return new OriginCounts(0, 0);
		}

		public int total() {
			return manual + autoGenerated;
		}
	}

	private GoldenProjectEventCounts() {}

	public static OriginCounts camera(Timeline timeline) {
		return countTrack(timeline, Timeline.TRACK_ID_CAMERA);
	}

	public static OriginCounts global(Timeline timeline) {
		return countTrack(timeline, Timeline.TRACK_ID_GLOBAL);
	}

	private static OriginCounts countTrack(Timeline timeline, String trackId) {
		Track track = timeline != null ? timeline.getTrack(trackId) : null;
		if (track == null) {
			return OriginCounts.zero();
		}
		int manual = 0;
		int autoGenerated = 0;
		for (Clip clip : track.getClips()) {
			if (TimelineClipOrigin.isAutoGenerated(clip, trackId)) {
				autoGenerated++;
			} else {
				manual++;
			}
		}
		return new OriginCounts(manual, autoGenerated);
	}
}
