package com.beatblock.timeline.project.golden;

import com.beatblock.audio.analysis.AudioFeatureTimeline;
import com.beatblock.audio.analysis.DetectedBeat;
import com.beatblock.audio.analysis.EnergyFrame;
import com.beatblock.audio.analysis.FrequencyBands;
import com.beatblock.BeatBlock;
import com.beatblock.automap.choreography.ChoreographyPlan;
import com.beatblock.automap.choreography.ChoreographyPlanEditor;
import com.beatblock.automap.choreography.ChoreographyPlanStore;
import com.beatblock.automap.choreography.SectionEditProfile;
import com.beatblock.automap.engine.AutoMapSettings;
import com.beatblock.automap.engine.Complexity;
import com.beatblock.automap.engine.SmartAutoMapEngine;
import com.beatblock.engine.StageObjectSystem;
import com.beatblock.engine.layer.BuildLayer;
import com.beatblock.engine.layer.BuildLayerManager;
import com.beatblock.test.WithBeatBlockContext;
import com.beatblock.testutil.MinecraftTestBootstrap;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.project.OscProjectStore;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 回归：手工 Camera/VFX 在 Smart Auto Map 重跑与 Section 编辑后仍保留，自动内容不重复叠加。
 */
@WithBeatBlockContext
class ManualPlusAutomapRegressionTest {

	@BeforeAll
	static void bootstrapMinecraft() {
		MinecraftTestBootstrap.ensureInitialized();
	}

	@TempDir
	Path tempDir;

	@Test
	void preservesManualEventsAcrossAutomapRerunsAndSectionEdits() throws Exception {
		Path source = GoldenProjectRegressionHarness.copyResourceTo(tempDir, "manual-plus-automap.osc");
		LoadedProject loaded = loadProject(source);
		registerStagesForAutomap(loaded.layers());
		GoldenProjectRegressionHarness.prepareEngine(loaded.timeline(), loaded.layers());

		assertBaselineManualCounts(loaded.timeline());

		AutoMapSettings settings = automapSettings();
		AudioFeatureTimeline feature = sampleFeatureTimeline(loaded.timeline().getDurationSeconds());

		SmartAutoMapEngine.generate(feature, settings, loaded.timeline());
		GoldenProjectEventCounts.OriginCounts manualCameraAfterFirst = assertManualPreserved(
			loaded.timeline(), 2, 2);
		GoldenProjectEventCounts.OriginCounts autoCameraAfterFirst = GoldenProjectEventCounts.camera(loaded.timeline());
		GoldenProjectEventCounts.OriginCounts autoVfxAfterFirst = GoldenProjectEventCounts.global(loaded.timeline());
		assertTrue(autoCameraAfterFirst.autoGenerated() > 0, "expected auto camera events after first automap");
		assertTrue(autoVfxAfterFirst.autoGenerated() > 0, "expected auto vfx events after first automap");

		SmartAutoMapEngine.generate(feature, settings, loaded.timeline());
		assertManualPreserved(loaded.timeline(), 2, 2);
		assertEquals(autoCameraAfterFirst, GoldenProjectEventCounts.camera(loaded.timeline()),
			"auto camera count changed after second automap");
		assertEquals(autoVfxAfterFirst, GoldenProjectEventCounts.global(loaded.timeline()),
			"auto vfx count changed after second automap");

		ChoreographyPlan plan = ChoreographyPlanStore.loadPlan(loaded.timeline());
		assertNotNull(plan);
		plan = ChoreographyPlanEditor.withSectionEdit(plan,
			SectionEditProfile.defaults(0).withMotionAnimationType("spin"));
		plan = ChoreographyPlanEditor.bakePhraseOverrides(plan);
		ChoreographyPlanStore.save(loaded.timeline(), plan, ChoreographyPlanStore.loadConfig(loaded.timeline()));

		SmartAutoMapEngine.generate(feature, settings, loaded.timeline());
		assertManualPreserved(loaded.timeline(), 2, 2);
		assertEquals(autoCameraAfterFirst, GoldenProjectEventCounts.camera(loaded.timeline()),
			"auto camera count changed after section edit");
		assertEquals(autoVfxAfterFirst, GoldenProjectEventCounts.global(loaded.timeline()),
			"auto vfx count changed after section edit");
		assertEquals(manualCameraAfterFirst, GoldenProjectEventCounts.camera(loaded.timeline()));
	}

	private static void assertBaselineManualCounts(Timeline timeline) {
		assertEquals(2, GoldenProjectEventCounts.camera(timeline).manual());
		assertEquals(2, GoldenProjectEventCounts.global(timeline).manual());
		assertEquals(0, GoldenProjectEventCounts.camera(timeline).autoGenerated());
		assertEquals(0, GoldenProjectEventCounts.global(timeline).autoGenerated());
	}

	private static GoldenProjectEventCounts.OriginCounts assertManualPreserved(
		Timeline timeline,
		int expectedManualCamera,
		int expectedManualVfx
	) {
		GoldenProjectEventCounts.OriginCounts camera = GoldenProjectEventCounts.camera(timeline);
		GoldenProjectEventCounts.OriginCounts global = GoldenProjectEventCounts.global(timeline);
		assertEquals(expectedManualCamera, camera.manual(), "manual camera count changed");
		assertEquals(expectedManualVfx, global.manual(), "manual vfx count changed");
		return camera;
	}

	private static AutoMapSettings automapSettings() {
		AutoMapSettings settings = new AutoMapSettings();
		settings.setComplexity(Complexity.MEDIUM);
		settings.setCameraEnabled(true);
		settings.setParticlesEnabled(true);
		settings.setTargetObjectIds(List.of("stage-main"));
		return settings;
	}

	private static AudioFeatureTimeline sampleFeatureTimeline(double durationSeconds) {
		return new AudioFeatureTimeline(
			durationSeconds,
			List.of(
				new DetectedBeat(1.0, 0.8f),
				new DetectedBeat(2.0, 0.75f),
				new DetectedBeat(4.0, 0.7f),
				new DetectedBeat(8.0, 0.85f),
				new DetectedBeat(12.0, 0.9f),
				new DetectedBeat(16.0, 0.8f),
				new DetectedBeat(24.0, 0.85f),
				new DetectedBeat(32.0, 0.7f)
			),
			List.of(
				new EnergyFrame(0.0, 0.2f),
				new EnergyFrame(8.0, 0.35f),
				new EnergyFrame(16.0, 0.55f),
				new EnergyFrame(24.0, 0.9f),
				new EnergyFrame(32.0, 0.45f),
				new EnergyFrame(durationSeconds - 1.0, 0.1f)
			),
			List.of(
				new FrequencyBands(1.0, 0.8f, 0.1f, 0.1f),
				new FrequencyBands(2.0, 0.1f, 0.7f, 0.2f),
				new FrequencyBands(4.0, 0.1f, 0.1f, 0.8f),
				new FrequencyBands(8.0, 0.85f, 0.2f, 0.15f),
				new FrequencyBands(12.0, 0.2f, 0.75f, 0.25f),
				new FrequencyBands(16.0, 0.15f, 0.15f, 0.85f),
				new FrequencyBands(24.0, 0.9f, 0.25f, 0.2f),
				new FrequencyBands(32.0, 0.2f, 0.2f, 0.75f)
			),
			new com.beatblock.audio.analysis.WaveformExtractor.WaveformFrame[0],
			128f,
			null
		);
	}

	private static void registerStagesForAutomap(BuildLayerManager layers) {
		if (layers == null || BeatBlock.getContext() == null || BeatBlock.getContext().blockAnimationEngine() == null) {
			return;
		}
		var stageSystem = BeatBlock.getContext().blockAnimationEngine().getStageObjectSystem();
		for (BuildLayer layer : layers.getAll()) {
			stageSystem.register(layer.getStageObject());
		}
	}

	private static LoadedProject loadProject(Path projectFile) throws Exception {
		BuildLayerManager layers = new BuildLayerManager(new StageObjectSystem());
		Timeline timeline = Timeline.createDefault();
		OscProjectStore.load(projectFile, layers, timeline);
		return new LoadedProject(timeline, layers);
	}

	private record LoadedProject(Timeline timeline, BuildLayerManager layers) {}
}
