package com.beatblock.timeline;

import org.jspecify.annotations.Nullable;

import java.util.HashMap;
import java.util.Map;

/** 在事件参数中读写 {@link TimelineEventOrigin}。 */
public final class TimelineEventOriginSupport {

	public static final String PARAM_KEY = TimelineClipOrigin.PARAM_KEY;

	private TimelineEventOriginSupport() {}

	public static Map<String, Object> withOrigin(@Nullable Map<String, Object> params, TimelineEventOrigin origin) {
		Map<String, Object> copy = params != null ? new HashMap<>(params) : new HashMap<>();
		TimelineEventOrigin resolved = origin != null ? origin : TimelineEventOrigin.MANUAL;
		copy.put(PARAM_KEY, resolved.name());
		return copy;
	}

	public static Map<String, Object> manualOrigin(@Nullable Map<String, Object> params) {
		return withOrigin(params, TimelineEventOrigin.MANUAL);
	}

	public static Map<String, Object> autoGeneratedOrigin(@Nullable Map<String, Object> params) {
		return withOrigin(params, TimelineEventOrigin.AUTO_GENERATED);
	}
}
