package com.beatblock.timeline;

import com.beatblock.timeline.camera.CameraTrackFactory;
import org.jspecify.annotations.Nullable;

import java.util.Map;

/**
 * 解析摄像机 / 全局事件 clip 的来源，供选择性清理自动草稿时保留手工内容。
 */
public final class TimelineClipOrigin {

	public static final String PARAM_KEY = "eventOrigin";

	private TimelineClipOrigin() {}

	public static TimelineEventOrigin originFromParameters(@Nullable Map<String, Object> params) {
		if (params == null) return TimelineEventOrigin.MANUAL;
		return TimelineEventOrigin.fromValue(params.get(PARAM_KEY));
	}

	public static boolean isAutoGenerated(@Nullable Clip clip, @Nullable String trackId) {
		if (clip == null || trackId == null) return false;
		if (Timeline.TRACK_ID_CAMERA.equals(trackId)) {
			return isAutoGeneratedCameraClip(clip);
		}
		if (Timeline.TRACK_ID_GLOBAL.equals(trackId)) {
			return isAutoGeneratedGlobalClip(clip);
		}
		return false;
	}

	private static boolean isAutoGeneratedCameraClip(Clip clip) {
		TimelineEvent segment = CameraTrackFactory.findSegmentHeadEvent(clip);
		if (segment != null) {
			return originFromParameters(segment.getParameters()) == TimelineEventOrigin.AUTO_GENERATED;
		}
		for (TimelineEvent event : clip.getEvents()) {
			if (event.getType() == EventType.CAMERA_KEYFRAME) {
				return originFromParameters(event.getParameters()) == TimelineEventOrigin.AUTO_GENERATED;
			}
		}
		return false;
	}

	private static boolean isAutoGeneratedGlobalClip(Clip clip) {
		for (TimelineEvent event : clip.getEvents()) {
			if (event.getType() != EventType.GLOBAL) continue;
			return originFromParameters(event.getParameters()) == TimelineEventOrigin.AUTO_GENERATED;
		}
		return false;
	}
}
