package com.beatblock.automap;

import com.beatblock.BeatBlock;
import com.beatblock.timeline.FeatureEvent;
import com.beatblock.timeline.FeatureTrack;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;
import com.beatblock.timeline.generation.TimelineDraftWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 根据特征轨事件与规则生成时间线动画草稿，经 {@link TimelineDraftWriter} 写入（可 Undo）。
 */
public final class AutoMapGenerator {

	private static final Logger LOGGER = LoggerFactory.getLogger(AutoMapGenerator.class);

	public static final String DEFAULT_TARGET_ID = "default";

	public static int generate(Timeline timeline, AutoMapConfig config, boolean replace) {
		if (timeline == null || config == null) return 0;

		Map<String, FeatureTrack> tracks = timeline.getFeatureTracks();
		if (tracks.isEmpty()) {
			LOGGER.info("BeatBlock Smart Auto Map: 无特征轨事件，请先导入音乐");
			return 0;
		}

		String targetId = resolveTargetObjectId();
		List<AutoMapRule> rules = config.getRules();
		double minGap = config.getMinGapSeconds();
		double lastTime = -minGap - 1;
		List<TimelineAnimationEvent> draft = new ArrayList<>();

		for (Map.Entry<String, FeatureTrack> entry : tracks.entrySet()) {
			String trackKey = entry.getKey();
			FeatureTrack track = entry.getValue();
			if (track == null || track.getEvents().isEmpty()) continue;
			for (FeatureEvent e : track.getEvents()) {
				if (e.getTimeSeconds() < lastTime + minGap) continue;
				AutoMapRule rule = findRule(rules, trackKey, e.getEnergy());
				if (rule == null) continue;

				Map<String, Object> params = new HashMap<>();
				if (rule.isUseEnergyForHeight()) {
					float h = e.getEnergy() * rule.getHeightMultiplier();
					params.put("height", h);
				}
				params.put("energy", e.getEnergy());

				draft.add(new TimelineAnimationEvent(
					"",
					e.getTimeSeconds(),
					rule.getDurationSeconds(),
					rule.getAnimationTypeId(),
					targetId,
					e.getEnergy(),
					params
				));
				lastTime = e.getTimeSeconds();
			}
		}

		int count = TimelineDraftWriter.writeAutoGeneratedEvents(timeline, draft, replace);
		LOGGER.info("BeatBlock Smart Auto Map: 已生成 {} 个动画草稿（目标: {}）", count, targetId);
		return count;
	}

	public static void clearAutoAnimationEvents(Timeline timeline) {
		if (timeline == null) return;
		timeline.clearAutoAnimationEvents();
	}

	private static AutoMapRule findRule(List<AutoMapRule> rules, String featureKey, float energy) {
		String normalized = normalizeFeatureKey(featureKey);
		for (AutoMapRule r : rules) {
			if (normalizeFeatureKey(r.getFeatureKey()).equals(normalized) && energy >= r.getMinEnergy()) {
				return r;
			}
		}
		return null;
	}

	private static String normalizeFeatureKey(String key) {
		if (key == null) return "low";
		return switch (key.toLowerCase()) {
			case "kick", "bass", "sub", "low", "drums" -> "low";
			case "snare", "snare_hi", "mid" -> "mid";
			case "hihat", "hat", "hihat_open", "high" -> "high";
			default -> key.toLowerCase();
		};
	}

	private static String resolveTargetObjectId() {
		if (BeatBlock.stageManager != null && BeatBlock.stageManager.getCurrentStage().isPresent()) {
			return BeatBlock.stageManager.getCurrentStage().get().getId();
		}
		return DEFAULT_TARGET_ID;
	}
}
